import json, sys

NEW_CONTENT = (
    '<div style="background:#e8f5e9;border-left:4px solid #22c55e;border-radius:0 8px 8px 0;padding:16px 20px;margin-bottom:28px;font-size:0.95em;line-height:1.8;color:#1a1a1a">'
    'このページでは、2026年最新のVPNサービスを速度・料金・安全性の3軸で厳選比較します。海外旅行・テレワーク・ストリーミング視聴など用途別に最適なVPNがすぐわかります。'
    '</div>\n\n'
    '<h2>おすすめVPN比較表（1位〜5位）</h2>\n'
    '<div style="overflow-x:auto;margin:16px 0">\n'
    '<table style="width:100%;border-collapse:collapse;min-width:560px">\n'
    '<thead>\n'
    '<tr style="background:#f0f0f0">\n'
    '<th style="padding:10px 12px;border:1px solid #e0e0e0;text-align:left;font-size:0.9em;white-space:nowrap">VPN</th>\n'
    '<th style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center;font-size:0.9em;white-space:nowrap">月額（最安）</th>\n'
    '<th style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center;font-size:0.9em;white-space:nowrap">速度</th>\n'
    '<th style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center;font-size:0.9em;white-space:nowrap">同時接続</th>\n'
    '<th style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center;font-size:0.9em;white-space:nowrap">返金保証</th>\n'
    '<th style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center;font-size:0.9em;white-space:nowrap">特徴</th>\n'
    '</tr>\n'
    '</thead>\n'
    '<tbody>\n'
    '<tr style="background:#fff8f0">\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;font-weight:700">&#x1F947; NordVPN</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">約490円〜</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">★★★★★</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">6台</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">30日</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0">速度・安全性No.1</td>\n'
    '</tr>\n'
    '<tr>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;font-weight:700">&#x1F948; Surfshark</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">約260円〜</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">★★★★☆</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">無制限</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">30日</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0">コスパ最強・家族利用</td>\n'
    '</tr>\n'
    '<tr style="background:#fff8f0">\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;font-weight:700">&#x1F949; ExpressVPN</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">約1,200円〜</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">★★★★★</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">8台</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">30日</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0">安定性重視の定番</td>\n'
    '</tr>\n'
    '<tr>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;font-weight:700">4位 CyberGhost</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">約280円〜</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">★★★★☆</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">7台</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">45日</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0">超長い返金保証期間</td>\n'
    '</tr>\n'
    '<tr style="background:#fff8f0">\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;font-weight:700">5位 MillenVPN</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">369円〜</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">★★★☆☆</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">5台</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0;text-align:center">30日</td>\n'
    '<td style="padding:10px 12px;border:1px solid #e0e0e0">日本語完全対応</td>\n'
    '</tr>\n'
    '</tbody>\n'
    '</table>\n'
    '</div>\n\n'
    '<h2>&#x1F947; 1位：NordVPN｜速度・安全性・実績No.1</h2>\n'
    '<p>世界シェアNo.1のVPN。独自プロトコル「NordLynx」で業界最速水準を実現し、NetflixやDAZNなど動画配信との相性も抜群です。ノーログポリシーを第三者機関が監査済みで、安全性は折り紙付き。6,000台超のサーバーで世界111カ国に接続でき、30日間全額返金保証でリスクなく試せます。</p>\n'
    '<p style="font-size:0.9em;color:#555;margin-top:-8px"><strong>月額:</strong> 約490円〜（2年プラン）&#xFF5C;<strong>同時接続:</strong> 6台&#xFF5C;<strong>返金保証:</strong> 30日</p>\n\n'
    '<div style="margin:28px 0;padding:20px 24px;background:linear-gradient(135deg,#fff8f0,#fff3e8);border-radius:14px;text-align:center;border:2px solid #ff6b35;">\n'
    '<a href="https://go.nordvpn.net/aff_c?offer_id=15&aff_id=142267" target="_blank" rel="noopener sponsored" style="display:inline-block;background:linear-gradient(135deg,#ff6b35,#e84d0e);color:#fff;padding:14px 40px;border-radius:10px;font-weight:bold;text-decoration:none;font-size:1.05em;box-shadow:0 4px 15px rgba(255,107,53,.4);">NordVPNを30日無料で試す &#x2192;</a>\n'
    '<p style="color:#999;font-size:.8em;margin-top:8px">30日間全額返金保証&#xFF5C;最短5分で使用開始</p>\n'
    '</div>\n\n'
    '<h2>&#x1F948; 2位：Surfshark｜同時接続無制限・コスパ最強</h2>\n'
    '<p>同時接続台数が無制限で、家族全員のスマホ・PC・タブレットを1アカウントで守れます。月額約260円〜という低価格も魅力で、「コスパ最優先」の方にベストな選択肢です。CleanWebで広告・マルウェアも自動ブロックし、30日間返金保証付きで安心して試せます。</p>\n'
    '<p style="font-size:0.9em;color:#555;margin-top:-8px"><strong>月額:</strong> 約260円〜（2年プラン）&#xFF5C;<strong>同時接続:</strong> 無制限&#xFF5C;<strong>返金保証:</strong> 30日</p>\n\n'
    '<div style="margin:28px 0;padding:20px 24px;background:linear-gradient(135deg,#fff8f0,#fff3e8);border-radius:14px;text-align:center;border:2px solid #ff6b35;">\n'
    '<a href="https://get.surfshark.net/aff_c?offer_id=926&aff_id=45127" target="_blank" rel="noopener sponsored" style="display:inline-block;background:linear-gradient(135deg,#ff6b35,#e84d0e);color:#fff;padding:14px 40px;border-radius:10px;font-weight:bold;text-decoration:none;font-size:1.05em;box-shadow:0 4px 15px rgba(255,107,53,.4);">Surfsharkを30日無料で試す &#x2192;</a>\n'
    '<p style="color:#999;font-size:.8em;margin-top:8px">同時接続無制限&#xFF5C;30日間返金保証</p>\n'
    '</div>\n\n'
    '<h2>&#x1F949; 3位：ExpressVPN｜安定性重視の定番VPN</h2>\n'
    '<p>VPN業界の老舗で、長年にわたって安定した品質を提供しています。独自プロトコル「Lightway」は速度と安全性を両立し、ストリーミングや出張時の利用に最適です。8台同時接続対応、94カ国3,000台以上のサーバーで接続先は豊富。30日間返金保証あり。</p>\n'
    '<p style="font-size:0.9em;color:#555;margin-top:-8px"><strong>月額:</strong> 約1,200円〜（1年プラン）&#xFF5C;<strong>同時接続:</strong> 8台&#xFF5C;<strong>返金保証:</strong> 30日</p>\n\n'
    '<h2>4位：CyberGhost｜45日返金保証で最もリスクゼロ</h2>\n'
    '<p>業界最長クラスの45日間返金保証が最大の特徴。初めてVPNを試す方が「失敗したくない」という場合に最適です。90カ国以上9,000台超のサーバーを持ち、Netflix専用サーバーも用意されています。7台同時接続対応でファミリー利用にも最適です。</p>\n'
    '<p style="font-size:0.9em;color:#555;margin-top:-8px"><strong>月額:</strong> 約280円〜（2年プラン）&#xFF5C;<strong>同時接続:</strong> 7台&#xFF5C;<strong>返金保証:</strong> 45日</p>\n\n'
    '<h2>5位：MillenVPN｜日本語対応・初心者向け国産VPN</h2>\n'
    '<p>日本語サポートが充実した国産VPN。「英語が不安」「初めてVPNを使う」という方に最適で、サポートページも日本語で整備されています。国内での通信速度も安定しており、70カ国以上に対応。クレジットカード・PayPalで支払い可能です。</p>\n'
    '<p style="font-size:0.9em;color:#555;margin-top:-8px"><strong>月額:</strong> 369円〜&#xFF5C;<strong>同時接続:</strong> 5台&#xFF5C;<strong>返金保証:</strong> 30日</p>\n\n'
    '<div style="margin:28px 0;padding:20px 24px;background:linear-gradient(135deg,#fff8f0,#fff3e8);border-radius:14px;text-align:center;border:2px solid #ff6b35;">\n'
    '<a href="https://px.a8.net/svt/ejp?a8mat=4AZSSR+66O50Y+3JTE+HV7V6" target="_blank" rel="noopener sponsored" style="display:inline-block;background:linear-gradient(135deg,#ff6b35,#e84d0e);color:#fff;padding:14px 40px;border-radius:10px;font-weight:bold;text-decoration:none;font-size:1.05em;box-shadow:0 4px 15px rgba(255,107,53,.4);">MillenVPNを申し込む &#x2192;</a>\n'
    '<p style="color:#999;font-size:.8em;margin-top:8px">日本語サポート対応&#xFF5C;30日間返金保証</p>\n'
    '</div>\n\n'
    '<h2>VPNの選び方（3つのポイント）</h2>\n'
    '<ol>\n'
    '<li><strong>速度</strong>：動画視聴・テレワークに支障ない速度か。プロトコルで大差あり（NordLynx・Lightway等が高速）</li>\n'
    '<li><strong>セキュリティ</strong>：ノーログポリシーと第三者監査の有無を必ず確認する</li>\n'
    '<li><strong>対応デバイス数</strong>：スマホ・PC・タブレット全部で使うなら同時接続台数が多いものを選ぶ</li>\n'
    '</ol>\n\n'
    '<div style="background:#fff8e1;border:1px solid #fbbf24;border-radius:8px;padding:14px 18px;margin:20px 0;font-size:0.9em;line-height:1.75">&#x26A1; <strong>ポイント：</strong>無料VPNは速度制限・ログ記録・広告表示などのリスクがあります。月額200〜500円程度の有料VPNを強く推奨します。</div>\n\n'
    '<div style="margin:36px 0;background:#f8f9fa;border-radius:10px;padding:20px 24px;border:1px solid #e8e8e8">'
    '<h2 style="margin:0 0 16px;font-size:1.05em;font-weight:800;color:#1a1a1a">よくある質問（FAQ）</h2>'
    '<div style="border-bottom:1px solid #e8e8e8;padding:14px 0">'
    '<h3 style="font-size:0.95em;font-weight:700;margin:0 0 8px;color:#1a1a1a">Q. 無料VPNは危険ですか？</h3>'
    '<p style="margin:0;color:#444;line-height:1.75;font-size:0.9em">無料VPNの多くは速度制限・データ上限・ログの第三者販売・広告挿入などのリスクがあります。プライバシーを本気で守りたい場合は有料VPNの利用を強く推奨します。</p>'
    '</div>'
    '<div style="border-bottom:1px solid #e8e8e8;padding:14px 0">'
    '<h3 style="font-size:0.95em;font-weight:700;margin:0 0 8px;color:#1a1a1a">Q. 初心者向けVPNはどれですか？</h3>'
    '<p style="margin:0;color:#444;line-height:1.75;font-size:0.9em">日本語サポートが充実しているMillenVPN、または日本語アプリが使いやすいNordVPNがおすすめです。いずれも30日間返金保証があるので失敗しません。</p>'
    '</div>'
    '<div style="border-bottom:1px solid #e8e8e8;padding:14px 0">'
    '<h3 style="font-size:0.95em;font-weight:700;margin:0 0 8px;color:#1a1a1a">Q. iPhoneでも使えますか？</h3>'
    '<p style="margin:0;color:#444;line-height:1.75;font-size:0.9em">はい。NordVPN・Surfshark・MillenVPN・ExpressVPN・CyberGhostはいずれもiOS・Android対応アプリがあります。スマホへの設定は数分で完了します。</p>'
    '</div>'
    '<div style="border-bottom:1px solid #e8e8e8;padding:14px 0">'
    '<h3 style="font-size:0.95em;font-weight:700;margin:0 0 8px;color:#1a1a1a">Q. 学校・職場のWi-FiでVPNは使えますか？</h3>'
    '<p style="margin:0;color:#444;line-height:1.75;font-size:0.9em">技術的には使用できます。ただし組織のポリシーによっては禁止されている場合があるため事前確認を推奨します。NordVPNは難読化サーバーで接続制限を回避できます。</p>'
    '</div>'
    '<div style="padding:14px 0">'
    '<h3 style="font-size:0.95em;font-weight:700;margin:0 0 8px;color:#1a1a1a">Q. VPNで何ができますか？</h3>'
    '<p style="margin:0;color:#444;line-height:1.75;font-size:0.9em">主な用途は3つ。&#9312;公共Wi-Fiでの通信暗号化（セキュリティ強化）、&#9313;海外から日本のNetflix・TVer等を視聴、&#9314;テレワーク時に会社ネットワークへ安全に接続。</p>'
    '</div>'
    '</div>\n\n'
    '<h2>まとめ：用途別おすすめVPN</h2>\n'
    '<ul>\n'
    '<li>&#x1F3C6; <strong>速度・安全性重視</strong> &#x2192; NordVPN</li>\n'
    '<li>&#x1F4B0; <strong>家族・複数台・コスパ重視</strong> &#x2192; Surfshark</li>\n'
    '<li>&#x1F530; <strong>初めてのVPN・日本語サポート必須</strong> &#x2192; MillenVPN</li>\n'
    '<li>&#x23F1;&#xFE0F; <strong>返金保証を長く使いたい</strong> &#x2192; CyberGhost（45日）</li>\n'
    '<li>&#x1F30D; <strong>安定性重視・出張多め</strong> &#x2192; ExpressVPN</li>\n'
    '</ul>\n'
    '<p>いずれも30日間（CyberGhostは45日間）の返金保証があるため、まず試してみて合わなければ返金申請できます。</p>\n'
    '<div style="margin:28px 0;padding:20px 24px;background:linear-gradient(135deg,#fff8f0,#fff3e8);border-radius:14px;text-align:center;border:2px solid #ff6b35;">\n'
    '<a href="https://go.nordvpn.net/aff_c?offer_id=15&aff_id=142267" target="_blank" rel="noopener sponsored" style="display:inline-block;background:linear-gradient(135deg,#ff6b35,#e84d0e);color:#fff;padding:14px 40px;border-radius:10px;font-weight:bold;text-decoration:none;font-size:1.05em;box-shadow:0 4px 15px rgba(255,107,53,.4);">まずはNordVPNを試してみる &#x2192;</a>\n'
    '<p style="color:#999;font-size:.8em;margin-top:8px">1位NordVPN&#xFF5C;30日間全額返金保証</p>\n'
    '</div>'
)

print(f"New content length: {len(NEW_CONTENT)} chars")

with open('C:/Users/ishid/claude-projects/bestnavi/data/posts.json', 'r', encoding='utf-8') as f:
    posts = json.load(f)

updated = False
for p in posts:
    if p.get('id') == 189:
        if isinstance(p.get('content'), dict):
            p['content']['rendered'] = NEW_CONTENT
        else:
            p['content'] = {'rendered': NEW_CONTENT}
        updated = True
        break

if not updated:
    print('ERROR: id=189 not found')
    sys.exit(1)

with open('C:/Users/ishid/claude-projects/bestnavi/data/posts.json', 'w', encoding='utf-8') as f:
    json.dump(posts, f, ensure_ascii=False, indent=2)

print("posts.json updated successfully")
